### PR TITLE
Dockerize Astro Workflow [WIP]

### PR DESCRIPTION
**Pull request by bjgavilanes**
Intended behaviour is to use pnpm run dev to run a node job and be able
to open localhost:4321 for development purposes.

While testing, I run pnpm run dev in host machine, and it does work! I
know is a problem in the dockerfile -- or docker-compose -- configuration.

Futher, I was able to deploy using docker run -port; so, yeah. I would
point at docker-compose.yml as the culprit, but I haven't gotten that far.

Can anyone help?

### CODE REVIEW

**Comment by bjgavilanes** [comment]
Can someone help a freedom volunteer?
@codediaz @davcortez @Jorgewlf88 @jhon-p16

**Comment by codediaz** [comment]
I'll proceed to review it! @bjgavilanes

**Comment by codediaz** [comment]
@bjgavilanes I’ve already addressed this issue in another MR, #46. The solution implemented there involves configuring docker-compose.yml to properly expose the necessary ports and ensure the app runs as expected on localhost:4321.

Feel free to check out MR #46 for details on the fix and let me know if you have any questions or if you'd like me to help with merging the changes!

**Comment by bjgavilanes** [comment]
Closed because we have #46 

Thanks again, @codediaz!,
@bjgavilanes

**Pull request closed without merging**
